version: '3'

services:
  postgres:
    #image: postgres
    build: ./dockerfilepostgres
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key -c ssl_ca_file=/var/lib/postgresql/root.crt -c hba_file=/etc/pg_hba.conf
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./certs3:/var/lib/postgresql
      - ./conf/pg_hba.conf:/etc/pg_hba.conf
    env_file:
        - postgres.env
    #ports:
    #  - 5432:5432

  keycloak:
    image: jboss/keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
      - ./certs:/etc/x509/https
      - ./certs2:/var/run/secrets/kubernetes.io/serviceaccount
      - ./root:/opt/jboss/.postgresql
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
      - "-Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    env_file:
    - keycloak.env
    ports:
    #  - 8080:8080
      - 8443:8443
    expose:
    #  - 8080
      - 8443
    depends_on:
      - postgres
      
  db:
    build: ./dockerfilemaria
    #image: mariadb:10.5-focal
    restart: always
    command: mysqld
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./mysql-cert:/etc/mysql/ssl
      - ./mariadbconf:/etc/mysql/conf.d
      - ./mariaencr:/etc/mysql/encryption/
    env_file:
    - maria.env
    #ports:
    #  - 3306:3306
         
  mosquitto:
    build: ./dockerfilemosquitto
    hostname: mosquitto
    volumes:
      - ./mosquitto-cert:/mosquitto/certs
      - ./mosquitto-config:/mosquitto/config
    #expose:
    #  - "8883"
    #ports:
    #  - 192.168.43.6:8883:8883

  web:
    build: ./spring
    command: java -jar /user/local/application/target.jar
    volumes:
      - ./spring/keystores:/keystores
      - ./spring/configEnc.xml:/configEnc.xml
    env_file:
    - spring.env
    expose:
      - "8081"
    ports:
      - 8081:8081
    depends_on:
      - db
      - mosquitto
      - keycloak
      
volumes:
    postgres_data:
      driver: local
