version: '3.1'

services:

  db:
    image: mariadb:10.5-focal
    #dockerfile:./Dockerfile
    restart: always
    command: mysqld --user=root
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
      - ./mysql-cert:/etc/mysql/ssl
      - ./mariadbconf:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: greenhouse
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
      
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
  #  volumes:
  #    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
  