version: '3.1'

services:
  web:
    build: .
    command: java -jar /user/local/application/target.jar
    volumes:
      - ./:/user/local/application
      - ./keystores:/keystores
    environment:
      XMLPASS: password
      KEYPASS: password
      TRUSTPASS: password
      DBPASS: password
      KEYCLOAKSECRET: 72d4cbe7-f6da-4746-929e-f835b76b5aab
      MOSQUITTOPASS: password
    expose:
      - "8081"
    ports:
      - "8081:8081"
    #network_mode: host
      
      