FROM openjdk:15-oraclelinux7
#RUN apt-get update
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/lib/:/usr/lib64/"
# Set environment
ENV JAVA_HOME /opt/jdk
ENV PATH ${PATH}:${JAVA_HOME}/bin   
ARG JAR_FILE=target.jar
COPY ${JAR_FILE} app.jar
COPY configEnc.xml configEnc.xml
#ENTRYPOINT ["java","-jar","/app.jar"]
#ENTRYPOINT ["java", "-jar", "/app.jar"]